//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public byte[] Image { get; set; }
        public string Card { get; set; }
        public string gender { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<bool> status { get; set; }
        public string role { get; set; }
    }
}
