//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDetail
    {
        public int orderId { get; set; }
        public string cakeId { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual tblCake tblCake { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
