//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShop
    {
        public string shopID { get; set; }
        public string shopAddress { get; set; }
        public string phone { get; set; }
    }
}
